 main: Archive.h Maximum.h Minimum.h Mean.h Median.h OutlinerCount.h Range.h Repository.h Sort.h StandardDeviation.h Main.cpp
	g++ -o main Archive.h Maximum.h Minimum.h Mean.h Median.h OutlinerCount.h Range.h Repository.h Sort.h StandardDeviation.h Main.cpp

.PHONY: clean
clean:
	rm -f *.gch
